name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.7"

      - name: Backend tests
        run: gradle -p apps/backend test

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Frontend build
        working-directory: apps/frontend-web
        run: |
          npm install --no-audit --no-fund
          npm run build

      - name: Build backend image
        run: docker build -t back:dev ./apps/backend

      - name: Build frontend image
        run: docker build -t front:dev ./apps/frontend-web

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.30.0"

      - name: Validate kustomize
        run: kubectl kustomize deploy/k8s/dev > /tmp/k8s-dev.yaml
