@baseUrl = http://localhost:8080
@endpointId = 00000000-0000-0000-0000-000000000001
@alertRuleId = 00000000-0000-0000-0000-000000000010
@alertEventId = 00000000-0000-0000-0000-000000000020
@nodeId = node-1

### Создать endpoint
POST {{baseUrl}}/api/endpoints
Content-Type: application/json

{
  "name": "Homepage",
  "url": "http://localhost:4430/status/200",
  "method": "GET",
  "headers": {
    "accept": "text/plain"
  },
  "timeoutMs": 3000,
  "expectedStatus": [
    200,
    399
  ],
  "intervalSec": 5,
  "enabled": true,
  "tags": [
    "public",
    "homepage"
  ]
}

### Список endpoints
GET {{baseUrl}}/api/endpoints

### Получить endpoint по id
GET {{baseUrl}}/api/endpoints/{{endpointId}}

### Обновить endpoint
PUT {{baseUrl}}/api/endpoints/{{endpointId}}
Content-Type: application/json

{
  "name": "Homepage",
  "url": "https://example.com/health",
  "method": "GET",
  "timeoutMs": 250,
  "expectedStatus": [
    200,
    399
  ],
  "intervalSec": 30,
  "enabled": true,
  "tags": [
    "public",
    "health"
  ]
}

### Удалить endpoint
DELETE {{baseUrl}}/api/endpoints/{{endpointId}}

### Статистика endpoint за окно
GET {{baseUrl}}/api/endpoints/{{endpointId}}/stats?windowSec=900

### Результаты проверок endpoint за интервал
GET {{baseUrl}}/api/endpoints/{{endpointId}}/checks?from=2024-01-01T00:00:00Z&to=2024-01-01T01:00:00Z

### Сводка по endpoints
GET {{baseUrl}}/api/endpoints/summary?windowSec=900

### Heartbeat backend-ноды
POST {{baseUrl}}/api/nodes/heartbeat
Content-Type: application/json

{
  "nodeId": "{{nodeId}}",
  "baseUrl": "http://localhost:8080",
  "startedAt": "2024-01-01T00:00:00Z",
  "meta": {
    "version": "0.0.1",
    "env": "local"
  }
}

### Список backend-нод
GET {{baseUrl}}/api/nodes

### Метрики backend-ноды
GET {{baseUrl}}/api/nodes/{{nodeId}}/metrics
